-- ============================================================
-- 005: EXPENSES TABLE
-- Core expense records — UUID generated by Flutter client
-- Supports offline-first with version control and soft deletes
-- ============================================================

CREATE TABLE IF NOT EXISTS public.expenses (
  id                UUID PRIMARY KEY,                -- Generated strictly by Flutter client
  group_id          UUID REFERENCES public.groups(id) ON DELETE SET NULL,  -- nullable for personal expenses
  paid_by           UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  created_by        UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  title             TEXT NOT NULL,
  description       TEXT,
  category          TEXT,
  total_amount      NUMERIC(12, 2) NOT NULL CHECK (total_amount > 0),
  split_mode        TEXT NOT NULL DEFAULT 'equal'
                    CHECK (split_mode IN ('equal', 'exact', 'percentage', 'chaos_roulette')),
  is_deleted        BOOLEAN NOT NULL DEFAULT FALSE,  -- Required for offline soft-deletes
  version           INTEGER NOT NULL DEFAULT 1,       -- Starts at 1, increments on edit
  expense_date      TIMESTAMPTZ,
  client_created_at TIMESTAMPTZ,                      -- Time recorded on device
  synced_at         TIMESTAMPTZ DEFAULT NOW()          -- Time recorded on server
);

COMMENT ON TABLE public.expenses IS 'Expense records with offline-first sync support (client-generated UUIDs)';
