-- ============================================================
-- 007: SETTLEMENTS TABLE
-- Payment records between users — UUID generated by Flutter client
-- Supports offline-first with version control
-- ============================================================

CREATE TABLE IF NOT EXISTS public.settlements (
  id                    UUID PRIMARY KEY,           -- Generated strictly by Flutter client
  group_id              UUID REFERENCES public.groups(id) ON DELETE SET NULL,  -- nullable
  payer_id              UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  payee_id              UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  amount                NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
  status                TEXT NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending', 'confirmed', 'rejected')),
  payment_method        TEXT,
  esewa_transaction_id  TEXT,
  note                  TEXT,
  version               INTEGER NOT NULL DEFAULT 1,
  client_created_at     TIMESTAMPTZ,
  confirmed_at          TIMESTAMPTZ,
  synced_at             TIMESTAMPTZ DEFAULT NOW(),

  -- Prevent self-settlement
  CONSTRAINT no_self_settlement CHECK (payer_id <> payee_id)
);

COMMENT ON TABLE public.settlements IS 'Settlement/payment records with eSewa integration and offline-first sync';
